version: 2.1
jobs:
  build:
    docker:
      - image: node:16.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
  validate:
    docker:
      - image: node:16.17.0
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
      - run:
          name: Lint
          command: yarn validate

workflows:
  version: 2
  build-and-validate:
    jobs:
      - build
      - validate:
          requires:
            - build
          filters:
            branches:
              only: /.*/
